config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #ルートパスにgroupsコントローラーのindexアクションを設定
  root "groups#index"
  #usersモデルのindex,edit,updateアクションのルーティングを設定
  resources :users, only: [:index, :edit, :update]
  #groupsモデルのnew,create,edit,updateアクションのルーティングを設定
  resources :groups, only: [:new, :create, :edit, :update] do
    #messagesモデルのindex,createアクションのルーティングを設定
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages
  validates :name, presence: true

  def show_last_message
    #最新のメッセージを変数last_messageに代入しつつ、メッセージが投稿されているかどうかで処理を分ける
    if (last_message == messages.last).present?
      #文章が投稿されている場合、さらに画像が投稿されているかで処理を分ける（三項演算子で記述）
      last_message_content? ? last_message.content : '画像が投稿されています'
    else
      'まだメッセージはありません'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  #groupsモデルとのアソシエーションを定義
  belongs_to :group
  #usersモデルとのアソシエーションを定義
  belongs_to :user
  #contentカラムのバリデーションを設定
  validates :content, presence: true, unless: :image?

  mount_uploader :image, ImageUpoader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :messages
  has_many :group_users
  has_many :groups, through: :group_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #未ログイン時にはログインページに遷移
  before_action :authenticate_user!
  #もしdevise_controllerが呼ばれたら、追加のパラメーターを許可するメソッドを呼び出す
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  #追加のパラメーターを許可するメソッドを定義
  def configure_permitted_parameters
    #サインアップ時にnameカラムをパラメーターとして渡すように設定
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
  end

  def new
    #groupsテーブルのインスタンスを生成してインスタンス変数を定義
    @group = Group.new
    #現在ログイン中のユーザーを新規作成したグループに追加
    @group.users << current_user
  end

  def create
    #ストロングパラメーターで設定した値をgroupsテーブルに保存して、インスタンス変数へ格納
    @group = Group.new(group_params)
    #もしgroupsテーブルに値が保存できたら
    if @group.save
      #トップページにリダイレクトしてフラッシュメッセージを表示
      redirect_to root_path, notice: 'グループを作成しました'
    else
      #renderを用いてHTTPリクエストを送らずnew.html.hamlを表示
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      #edit.html.hamlを描画
      render :edit
    end
  end

  private
  #ストロングパラメーターの設定
  def group_params
    #groupsモデルに制限してnameカラムのパラメーターを追加
    params.require(:group).permit(:name, user_ids: [] )
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  #before_actionでset_groupを呼び出すことで全てのアクションを行う前に@groupを利用できるように設定
  before_action :set_group
  def index
    #Messageモデルの新しいインスタンスを生成
    @message = Message.new
    #usersモデルの値も同時に取得することでN+1問題を解消してgroupに所属している全てのメッセージを取得してインスタンス変数へ格納
    @messages = group.messages.includes(:user)
  end

  def create
    #ストロングパラメーターで設定した値を取得してGroupsテーブルのmessageカラムの値を保存してインスタンス変数に格納
    @message = @group.messages.new(message_params)
    #もし値が保存出来たら、
    if @message.save
      #respond_to doを使用しリクエストされたフォーマットによって処理を分ける
      respond_to do |format|
        format.html { redirect_to group_messages_path(params[:group_id]) }
        #フォーマットがjsonの時rails newコマンドでアプリケーションを作成した際にgemfileにデフォルトで記述されているgemで、入力データをJSON形式で出力するテンプレートエンジンであるjbuilderを用いてJavaScriptに返すデータを作成
        #JSONを返す場合はRubyのハッシュの状態のままrenderメソッドに渡すだけでJSONに変換してくれるので、コントローラーから直接データを返すことができる
      format.json { render json: @message }
    end
      #redirect_to group_messages_path(@group), notice: 'メッセージが送信されました'
  else
    @messages = @group.messages.includes(:user)
    flash.now[:alert] = 'メッセージを入力してください'
    render:index
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end
  #group_idキーで送られてきたパラメーターの値をgroupsテーブルから取得してインスタンス変数へ格納するメソッドを定義
  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where('name LIKE(?)', "%#{params[:keyword]}%").limit(20)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
  end

  def update
    #もしログイン中のユーザーのテーブルの値が更新されたら
    if current_user.update(user_params)
      #トップページへリダイレクト
      redirect_to root_path
    else
      #editのビューを再描画
      render :edit
    end
  end

  private

  def user_params
    #userテーブルに制限して、nameカラムとemailカラムの値をパラメーターとして渡す
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
    /
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_チャットメンバーを追加"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input.chat-group-form__input#user-search-field{ placeholder: '追加したいユーザー名を入力してください' type: 'text'}

      #user-search-result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
      = f.collection_check_boxes :user_ids, User.all, :id, :name
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
      /
      %div{id: 'chat-group-users'}
      .chat-group-user.clearfix#chat-group-user-22
        %input{ name: 'chat_group[user_ids][]' type: 'hidden' value: '22'}
          %p.chat-group-user__name seo_kyohei
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }
  %form#edit_chat_group_22.edit_chat_group{"accept-charset" => "UTF-8", action: "/chat_groups/22", method: "post"}
    .chat-group-form__errors
      %h2
        1件のエラーが発生しました。
        %ul
          %li エラーです
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{for: "chat_group_name"} グループ名
      .chat-group-form__field--right
        %input#chat_group_name.chat-group-form__input{name: "chat_group[name]", placeholder: "グループ名を入力してください", :type: "text", value: "ほげー"}/
    .chat-group-form__field.clearfix
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
      .chat-group-form__field--left
      %label.chat-group-form__label{ for: "chat_group_チャットメンバーを追加"}チャットメンバーを追加
      .chat-group-form__field--right
      .chat-group-form__search.clearfix
      %input.chat-group-form__input{id: 'user-search-field' placeholder:'追加したいユーザー名を入力してください' type: 'text'}
      #user-search-result
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
        %input.chat-group-form__action-btn{"data-disable-with" => "Save", name: "commit", type: "submit", value: "Save"}/

app/views/groups/index.html.haml
.wrapper
  = render 'shared/side_bar'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', { group: @group }
  //groupsテーブルに値を保存する為のフォームを作成
  = form_for @group do |f|
  //もし保存の際にエラーが発生したら
    - if @group.errors.any?
    .chat-group-form__errors
    //errorの数を取得してエラー文を表示
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
        %ul
        //groupsテーブルのエラー文を取得してmessage変数に1つずつ格納
          - @group.errors.full_messages.each do |message|
          //格納したエラー文をを表示
            %li= message
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, class: 'chat-group-form__label'
      .chat-group-form__field--right
        = f.text_field :name, class: 'chat_group_name chat-group-form__input' placeholder: "グループ名を入力してください"
    .chat-group-form__field.clearfix
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
      .chat-group-form__field--left
        %label.chat-group-form__label{for: "chat_group_チャットメンバーを追加"} チャットメンバーを追加
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
        %input.chat-group-form__input#user-search-field{ placeholder: '追加したいユーザー名を入力してください' type: 'text'}
        #user-search-result
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバー
      .chat-group-form__field--right
        / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
        =f.collction_check_boxes :user_ids, User.all, :id, :name
        / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します

          #div{id: 'chat-group-users'}
            .chat-group-user.clearfix{ id: 'chat-group-user-22'}
            %input{ name: 'chat_group[user_ids][]', type: 'hidden', value: '22'}
            %p.chat-group-user__name seo_kyohei
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit class: 'chat-group-form__action-btn'

app/views/layouts/_notifications.html.haml
//フラッシュメッセージを表示させる為のビューを設定
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/_messages.html.haml
.message
  .upper-message
    .upper-message__user-name
      = message.user.name
      .upper-message__date
      =format_posted_time(message.cerated_at)
    .lower-message
      - if message.content.present?
       %p.lower-message__content
        = message.content
      =image_tag message.image.url, class: 'lower-message__image' if message.image.present?

app/views/messages/index.html.haml
.form
  = form_for [@group, @message] do |f|
    f.text_field :content,class:'form__message', placeholder: 'type a message'
    .form__mask
      = f.label :image, class: 'form__mask__image' do
        = fa_icon 'picture-o', class: 'icon'
        = f.file_field 'image', class: 'hidden'
      = f.submit 'Send', class: 'form__submit'
.message
  = render @messages

app/views/messages/index3.html.haml
.header
  %p チャットグループが作成されました。

.left
  .left__contents
    .left__contents--top
      .left__contents--name
        %p tatsuki-nakamura
          %ul.icon__cog
            %li.list
            =link_to root_path do
              = fa_icon 'pencil-square-o', class: 'icon'
            %li.list
              = fa_icon 'fa-cog', class: 'icon'
    .left__contents--bellow
      .left__contents--bellow-group
        %p techcamp
      .left__contents--bellow-message
        %p まだメッセージはありません
    .left__contents--bellow
      .left__contents--bellow-group
        %p sampleグループ
      .left__contents--bellow-message
        %p aaa
.right
  .right__contents
    .right__contents--top
      .right__contents--top-group
        %p techcamp
      .right__contents--top-member
        %p Members: tatsuki-nakamura
      .right__contents--top-button
        %p.inline Edit

    .right__contents--bellow
      .right__contents--bellow-name
        %p tatsuki-nakamura
      .right__contents--bellow-time
        %p 2018/07/07
      .right__contents--bellow-message
        %p sss

.right__footer
  .right__footer--message
    %form{:action => "#", :method => "post"}
    .right__footer--message-post
      %input{:type => "text", :name => "comments", placeholder: "type a message" }
  .right__footer--icon
    = link_to root_path do
      = fa_icon 'fa-image', class: 'icon'
  .right__footer--button
    %p send

app/views/shared/_side_bar.html.haml
.side-bar
  .header
    %h3.header__name
      = current_user.name
    %ul.header__lists
      %li.list
        = link_to new_group_path do
          = fa_icon 'pencil-square-o', class: 'icon'
      %li.list
        = link_to edit_user_path(current_user) do
          = fa_icon 'cog', class: 'icon'
  .groups
    - current_user.groups.each do |group|
      .group
        = link_to group_messages_path(group) do
          .group__name
            = group.name
          .group__message
            = group.show_last_message

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      //ログアウトボタンの生成
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      //トップページへのリンクを生成
      =link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "update", class: 'btn'